### PR TITLE
Login via OpenID

### PR DESCRIPTION
**Pull request by oiami**
Front-end part the of OpenID stuffs. :D

### CODE REVIEW

**Comment by oiami** [comment]
@rwstauner , Ok, I'll look at it :)

**Comment by oiami** [comment]
@rwstauner, I think I'm done. Could you please check ?

**Comment by oalders** [comment]
\p/

**Comment by rwstauner** [comment]
Awesome! :tada: Thanks, @oiami!  I'm glad to have this finally released.
Sorry for the long engagement ;-)

I did have to do the unfortunate "oops, logged in with new id and lost my old session - disconnect - log out - reconnect my usual - see multiple - add new id - hooray!" dance, but it worked!

**Comment by oalders** [comment]
This probably merits a NEWS entry.

**Comment by rwstauner** [comment]
Indeed.  Care to do the honors, @oiami?

**Pull request merged**
