### PR TITLE
Add setFavTitle in several places. Untested.

### PR DESCRIPTION
**Pull request by shlomif**
This is to fix the title attribute of the ++ buttons.

### CODE REVIEW

**Comment by oalders** [comment]
@shlomif thanks for this!  Would be great if someone could test/verify this.

**Comment by oalders** [comment]
@shlomif could you rebase this branch?

**Comment by shlomif** [comment]
Hi! I rebased it now.

**Comment by oalders** [comment]
Thanks!

**Comment by shlomif** [comment]
Thanks for merging @oalders ! And - you're welcome.

**Pull request merged**
