### PR TITLE
Add link to expand and collapse long change lists

### PR DESCRIPTION
**Pull request by bentglasstube**
Adds a link to expand and collapse large whatsnew sections.  The link text is hardcoded to be "Show More" and "Show Less" because I couldn't figure out how/if any internationalization code worked.  Some animation would make this look much nice, but I lack the jQuery/CSS chops for that.

### CODE REVIEW

**Comment by bentglasstube** [comment]
This related to issue #1585

**Comment by oalders** [comment]
This now has a merge conflict.  Would you be able to rebase?

**Comment by bentglasstube** [comment]
Rebased and force pushed, hopefully that works out okay with the pull request.

**Comment by oalders** [comment]
Thanks!

**Pull request merged**
