### PR TITLE
Elasticsearch v0 to v2

### PR DESCRIPTION
**Pull request by oalders**
This is the branch we'll merge into master to close out the long lived `mi/es2` branch.

### CODE REVIEW

**Comment by oalders** [comment]
@ranguard, @mickeyn  This is ready for merge now.

**Comment by mickeyn** [comment]
that's great, shall we merge it to master then?

quick question: will it not affect the v0 servers in any way (in case of puppet running)?

**Comment by ranguard** [comment]
I have switched bm-mc-01, bm-mc-02 and bm-mc-03 over to use: https://github.com/CPAN-API/metacpan-puppet/tree/legacy/v0 specifically note the `git_revision` https://github.com/CPAN-API/metacpan-puppet/blob/legacy/v0/hieradata/common.yaml#L88 https://github.com/CPAN-API/metacpan-puppet/blob/legacy/v0/hieradata/common.yaml#L103

I haven't actually run puppet under this new branch - but it should stop accidents

**Comment by mickeyn** [comment]
alright then, here goes...

**Comment by jberger** [comment]
\o/

**Pull request merged**
