### PR TITLE
schema.org markup fixed, unittest added

### LINKED ISSUE #1629: schema.org microdata broken
The schema.org microdata that was introduced with pull request #864 is currently broken (probably caused by a UI rework), as can be seen by [Google structured data test tool](https://developers.google.com/structured-data/testing-tool?url=https%253A%252F%252Fmetacpan.org%252Fpod%252FMoose&filter=RICH_SNIPPETS_SOFTWARE) not correctly showing 1 app with name, author, url, etc, but instead two apps with basically no data.

### PR DESCRIPTION
**Pull request by mephinet**
This patch fixes the schema.org microdata embedded in the metacpan POD page. The result can be seen in Google's Structured Data Testing Tool - see the screenshot:
example
Other pages that use the same includes are not affected at all.

I added a unittest to assure that things stay like that :-)
Fixes #1629.

### CODE REVIEW

**Comment by oalders** [comment]
:+1: Thanks!

**Comment by haarg** [comment]
This has messed up the layout on the sidebar.
screen shot 2016-01-14 at 12 47 37 pm

**Comment by mephinet** [comment]
one extra space in front of the (  ?


-------- Ursprüngliche Nachricht --------
Von: Graham Knop <notifications@github.com> 
Datum:14.01.2016  18:48  (GMT+01:00) 
An: CPAN-API/metacpan-web <metacpan-web@noreply.github.com> 
Cc: Philipp Gortan <mephinet@gmx.net> 
Betreff: Re: [metacpan-web] schema.org markup fixed, unittest added (#1633) 

This has messed up the layout on the sidebar.

**Comment by mephinet** [comment]
@haarg: correct - if the review is not an integer, but has a .5, it occupies to much horizontal space (even though hidden) that a line break occurs. I'll fix that!

**Pull request merged**
