### PR TITLE
Fix auto-complete authors label in search

### PR DESCRIPTION
**Pull request by xsawyerx**
Per GH #1707, when searching for authors, the auto-complete shows the found results under a label "Products". This adds a CSS rule to fix it and show them under a label "Authors".

### CODE REVIEW

**Comment by mickeyn** [comment]
can you please set the PR to mi/es2 instead of master?

**Comment by xsawyerx** [comment]
Done. Pushed force.

It seems like **master** and **mi/es2** have diverged in 4ad4eb9a93a3452b701a49d9b6e191d4252f05d9. I suggest rebase **mi/es2** on **master** or cherry-picking the commits (with updated `git` it's possible to cherry-pick a range), or merge it (eww, but yeah).

**Comment by xsawyerx** [comment]
I don't know how @haarg's commit got in there. :confused:

**Comment by xsawyerx** [comment]
Oh crap. I know how this happened. I'm an idiot. It's still against **master**.

**Pull request closed without merging**
